export const tags = { // TODO make map
    'DIV': true, 
    'BODY': true, 
    'H1': true, 
    'H2': true, 
    'H3': true, 
    'H4': true, 
    'H5': true, 
    'H6': true, 
    'P': true, 
    'UL': true, 
    'OL': true, 
    'LI': true, 
    'SPAN': true, 
    'TABLE': true,
    'IFRAME': true,
    'A': true,
    'TD': true,
    'TH': true,
    'TR': true,
    'MAIN': true,
    'HEADER': true,
    'ARTICLE': true,
    'LABEL': true,
};